### ISSUE TITLE
Issue in new version 2.003 (upgraded from personal from Basic)

### ISSUE THREAD

**Issue by freyjasasi** [MonoLisaFont/feedback#172]
We welcome any feedback regarding technical issues (broken letters, ligatures not working, bad spacing etc). We will have a look and try to implement the changes in future versions.

---

## Background information

To help debugging, fill the following information before describing the issue:

* Font edition (i.e. trial, personal, plus, pro): Basic
* Font version (i.e. 1.805): 2.003
* The type of the font file you are using (i.e. otf, ttf): ttf
* Operating system (i.e. MacOS, Windows): windows
* Display resolution (i.e. 3072x1920): 1920x1080
* Any other information that might be helpful: images attached, either its possible to install regular or bold. not able to install both in new version 2.003

## Issue

<img width="526" alt="image" src="https://user-images.githubusercontent.com/25368842/205416683-504739c6-7882-4f22-b50c-558c5824f788.png">
<img width="736" alt="image" src="https://user-images.githubusercontent.com/25368842/205416802-05dda47a-1137-42e6-af1d-dfe8e481b801.png">

**Comment by TheoryOfNekomata** [comment]
Same problem as mine. I did compare the internal names between v2 and v1, seems like the v2 names are wrong.

![image](https://user-images.githubusercontent.com/2346301/205418825-fe9cb091-7356-4e48-ba9d-05e184b0801c.png)

Left side is v1, right side is v2.

Notice that in the v2 it says "MonoLisa-Regular" despite having bold weight.

**Comment by bebraw** [comment]
This should be fixed now. The issue was that there was a range change and `SemiBold` was introduced as 600 and `Bold` moved to 700 in order to follow standard. Now Basic ships with the new Bold (700).

**Comment by bebraw** [comment]
Make sure to re-download to get the correct weight.

**Comment by freyjasasi** [comment]
> Make sure to re-download to get the correct weight.

Ok, i will check now. Thanks for quick response

**Comment by freyjasasi** [comment]
> Make sure to re-download to get the correct weight.

Hi @bebraw now weights are ok but names of font weight are still wrong 

<img width="473" alt="image" src="https://user-images.githubusercontent.com/25368842/205469510-35393648-4f07-4b74-9c7a-2dbc531804f6.png">

**Comment by bebraw** [comment]
@freyjasasi Thanks for the heads up, we're looking into the name issue now.

**Comment by bebraw** [comment]
@freyjasasi I just applied a related fix. When you have time, could you please re-download and confirm the names look correct?

**Comment by freyjasasi** [comment]
> @freyjasasi I just applied a related fix. When you have time, could you please re-download and confirm the names look correct?

Ok, thanks, will update once verified 👍

**Comment by freyjasasi** [comment]
Now font names are correct

**Comment by freyjasasi** [comment]
Now font names are correct
